#!/bin/bash

HAS_RSA_SET=$(cat /etc/ssh/sshd_config | grep "PubkeyAcceptedKeyTypes=+ssh-rsa")

if [[ $HAS_RSA_SET == "" ]]; then
  echo "PubkeyAcceptedKeyTypes=+ssh-rsa" >> /etc/ssh/sshd_config
  echo "Config added"
  exit 0
else
  echo "Config was already set. Ignoring..."
  exit 0
fi