name: CI

on:
  push:
    branches: [ main, adding-docker ]

  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      
      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          
      - name: Install Dependencies
        run: yarn
        
      - name: Build
        run: yarn build

      - name: Setting up SSH RSA Config
        run: chmod u+x ./deploy/ssh_ubuntu-server_rsa-config && ./deploy/ssh_ubuntu-server_rsa-config
        
      - uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: "./, !node_modules"
          target: "~/my-cli-browser"
          
      - name: Updating and Running Docker compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo apt update && sudo apt upgrade -y
            curl --version
            if [[ $? == 127 ]]; then
              sudo apt install curl
            fi
            ls /etc/apt/keyrings/docker.gpg
            if [[ $? == 2 ]]; then  
              sudo apt-get remove docker docker-engine docker.io containerd runc
              sudo apt install ca-certificates gnupg lsb-release -y
              sudo mkdir -p /etc/apt/keyrings
              curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg   
              echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
              sudo apt-get update
              sudo apt-get install docker-ce docker-ce-cli containerd.io docker-compose-plugin -y
              sudo apt update && sudo apt upgrade -y && sudo apt autoremove -y
            fi
            node -v
            if [[ $? == 127 ]]; then
              curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
              sudo apt-get install -y nodejs
            fi
            cd /home/ubuntu/my-cli-browser
            npm install -g npm
            npm install
            sudo docker-compose up --build -d
            