name: CI

on:
  push:
    branches: [ main, adding-docker ]

  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      
      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          
      - name: Install Dependencies
        run: yarn
        
      - name: Build
        run: yarn build

      - name: Setting up SSH RSA Config
        run: chmod u+x ./deploy/ssh_ubuntu-server_rsa-config && ./deploy/ssh_ubuntu-server_rsa-config
        
      - uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: "./, !node_modules"
          target: "~/my-cli-browser"
          
      - name: Updating and Running Docker compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ubuntu/my-cli-browser
            npm install
            docker-compose up --build -d
            